url: https://astoria.consulting
baseurl: 

# Site settings
title: ASTORIA
email: cory.eft@astoria.consulting
description: "Technology Consulting"


# Team names, titles and social links
people:
- name: Cory Eft
  pic: cory
  position: Founder

- name: Laura Eft
  pic: laura
  position: Founder

- name: Brian Eft
  pic: brian
  position: Founder

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    url: http://github.com/astoria_consulting

# Postal address (add as many lines as necessary)
address:
  - line: 1828 Chiprock Dr
  - line: Marysville, OH 43040

# Build settings
markdown: kramdown
permalink: pretty